name: Daily Commit

on:
  schedule:
    - cron: "0 8 * * *"  # каждый день в 10:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Make a commit
      run: |
        echo "$(date)" >> log.txt
        git config --global user.email "dm.2909@mail.ru"
        git config --global user.name "louvredprod"
        git add .
        git commit -m "Daily update"
        git push
